name: Deploy Github Page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -f
   # - run: npm test
    - run: npm run deploy

      env:
        CI: true
        # Deploy env
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} #